#version: '3'
services:
  # postgres:
  #   image: postgres:15
  #   environment:
  #     #- POSTGRES_PASSWORD=postgres
  #     #- POSTGRES_USER=postgres
  #     #- POSTGRES_DB=eliza
  #   volumes:
  #     - postgres-data:/root/.eliza/db
  #   ports:
  #     - '127.0.0.1:5432:5432'
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready -U postgres']
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - eliza-network
  #   restart: always
  solana:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solana
    command: "bash /opt/bootstrap/scripts/userdata.sh"
    stdin_open: true
    tty: true
    privileged: true

    volumes:      
      - /sys/fs/cgroup:/sys/fs/cgroup
    tmpfs:
      - /run
      - /tmp
            
    ports:
      - '8000:8000'
    
