name: Eliza CLI Tests

on:
  push:
    paths:
      - 'packages/cli/**'
      - '.github/workflows/cli-tests.yml'
  pull_request:
    paths:
      - 'packages/cli/**'
      - '.github/workflows/cli-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Setup Turbo Cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-


      - name: Build all packages
        run: bun turbo run build --filter=!@elizaos/docs

      - name: Install bats (npm)
        run: npm install -g bats

      - name: Make test scripts executable
        run: chmod +x packages/cli/__test_scripts__/*.bats packages/cli/__test_scripts__/*.sh

      

      - name: Run CLI shell tests
        run: ./run_all_bats.sh
        working-directory: packages/cli/__test_scripts__